command_timeout = 1000
[rust]
symbol = " "
[python]
symbol = " "
[kubernetes]
disabled = false
[lua]
symbol = " "
[terraform]
disabled = false
symbol = "󱁢 "
[java]
disabled = false
[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"
[golang]
symbol = " "
