vim.keymap.set("x", "<leader>ibl", "<cmd>CBlcbox<cr>", { desc = "Left aligned box" })
vim.keymap.set("x", "<leader>ibc", "<cmd>CBccbox<cr>", { desc = "Centered box" })
vim.keymap.set("x", "<leader>ibr", "<cmd>CBrcbox<cr>", { desc = "Right aligned box" })
vim.keymap.set("x", "<leader>ibd", "<cmd>CBd<cr>", { desc = "Delete box" })
vim.keymap.set("n", "<leader>il", "<cmd>CBcline<cr>", { desc = "Centered line" })
