require("git-conflict").setup()
vim.keymap.set("n", "<localleader>gmb", "<cmd>GitConflictChooseBoth<cr>", { desc = "Both" })
vim.keymap.set("n", "<localleader>gmj", "<cmd>GitConflictNextConflict<cr>", { desc = "Next conflict" })
vim.keymap.set("n", "<localleader>gmk", "<cmd>GitConflictPrevConflict<cr>", { desc = "Prev conflict" })
vim.keymap.set("n", "<localleader>gmn", "<cmd>GitConflictChooseNone<cr>", { desc = "None" })
vim.keymap.set("n", "<localleader>gmq", "<cmd>GitConflictListQf<cr>", { desc = "Quickfix conflicts" })
vim.keymap.set("n", "<localleader>gmo", "<cmd>GitConflictChooseOurs<cr>", { desc = "Ours" })
vim.keymap.set("n", "<localleader>gmt", "<cmd>GitConflictChooseTheirs<cr>", { desc = "Theirs" })
