require("nvim-treesitter-textobjects").setup({
  textobjects = {
    select = {
      lookahead = true,
    },
    move = {
      set_jumps = true, -- whether to set jumps in the jumplist
    },
  },
})
-- NOTE: SELECT keybinds
vim.keymap.set({ "n", "x", "o" }, "af", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@function.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "if", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@function.inner", "textobjects")
end)
-- o for object
vim.keymap.set({ "n", "x", "o" }, "ao", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@class.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "io", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@class.inner", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ac", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@conditional.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ic", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@conditional.inner", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ae", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@block.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ie", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@block.inner", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "al", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@loop.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "il", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@loop.inner", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "aa", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@parameter.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ia", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@parameter.inner", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "as", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@statement.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "ak", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@comment.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "am", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@call.outer", "textobjects")
end)
vim.keymap.set({ "n", "x", "o" }, "im", function()
  require("nvim-treesitter-textobjects.select").select_textobject("@call.inner", "textobjects")
end)
-- NOTE move keybinds
vim.keymap.set({ "n", "x", "o" }, "]f", function()
  require("nvim-treesitter-textobjects.move").goto_next_start("@function.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "]o", function()
  require("nvim-treesitter-textobjects.move").goto_next_start("@class.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "]a", function()
  require("nvim-treesitter-textobjects.move").goto_next_start("@parameter.inner")
end)
vim.keymap.set({ "n", "x", "o" }, "[f", function()
  require("nvim-treesitter-textobjects.move").goto_previous_start("@function.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "[o", function()
  require("nvim-treesitter-textobjects.move").goto_previous_start("@class.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "[a", function()
  require("nvim-treesitter-textobjects.move").goto_previous_start("@parameter.inner")
end)
vim.keymap.set({ "n", "x", "o" }, "]F", function()
  require("nvim-treesitter-textobjects.move").goto_next_end("@function.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "]O", function()
  require("nvim-treesitter-textobjects.move").goto_next_end("@class.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "]A", function()
  require("nvim-treesitter-textobjects.move").goto_next_end("@parameter.inner")
end)
vim.keymap.set({ "n", "x", "o" }, "[F", function()
  require("nvim-treesitter-textobjects.move").goto_previous_end("@function.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "[O", function()
  require("nvim-treesitter-textobjects.move").goto_previous_end("@class.outer")
end)
vim.keymap.set({ "n", "x", "o" }, "[A", function()
  require("nvim-treesitter-textobjects.move").goto_previous_end("@parameter.inner")
end)
