local ensure_installed = {
  "bash",
  "bibtex",
  "bicep",
  "c",
  "c_sharp",
  "clojure",
  "cmake",
  -- May have slow performance in large files
  -- "comment",
  "commonlisp",
  "cpp",
  "css",
  "cuda",
  "d",
  "dart",
  "diff",
  "devicetree",
  "dockerfile",
  "elixir",
  "elm",
  "erlang",
  "fennel",
  "fish",
  "foam",
  "fortran",
  "gitcommit",
  "gitignore",
  "git_rebase",
  "gdscript",
  "go",
  "gosum",
  "gotmpl",
  "gomod",
  "gowork",
  "graphql",
  "haskell",
  "hcl",
  "heex",
  "hjson",
  "html",
  "http",
  "ini",
  "java",
  "javascript",
  "jsdoc",
  "json",
  "jsonnet",
  "json5",
  "julia",
  "kdl",
  "kotlin",
  "latex",
  "llvm",
  "lua",
  "luap",
  "luadoc",
  "make",
  "markdown",
  "markdown_inline",
  "ninja",
  "nix",
  "nu",
  "ocaml",
  "ocaml_interface",
  "ocamllex",
  "pascal",
  "perl",
  "python",
  "ql",
  "query",
  "r",
  "rasi",
  "regex",
  "rego",
  "rst",
  "ruby",
  "rust",
  "scala",
  "scheme",
  "scss",
  "solidity",
  "svelte",
  "swift",
  "teal",
  "todotxt",
  "toml",
  "tmux",
  "tsx",
  "typescript",
  "typst",
  "vala",
  "vim",
  "vimdoc",
  "vue",
  "yaml",
} -- one of "all", "language", or a list of languages

vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  once = true,
  callback = function()
    require("nvim-treesitter").install(ensure_installed)
  end,
})

local ignored_filetypes = {
  "checkhealth",
  "lazy",
  "mason",
  "snacks_dashboard",
  "snacks_notif",
  "snacks_win",
  "snacks_input",
  "snacks_picker_input",
  "undotree",
  "vscode-diff-explorer",
  "fyler",
}

vim.api.nvim_create_autocmd("FileType", {
  callback = function(event)
    if vim.tbl_contains(ignored_filetypes, event.match) then
      return
    end
    pcall(vim.treesitter.start) -- errors for filetypes with no parser
  end,
  desc = "Enable treesitter highlighting",
})
