vim.api.nvim_set_keymap("n", "*", "<Plug>(asterisk-*)", {})
vim.api.nvim_set_keymap("n", "#", "<Plug>(asterisk-#)", {})
vim.api.nvim_set_keymap("n","g*", "<Plug>(asterisk-g*)", {})
vim.api.nvim_set_keymap("n","g#", "<Plug>(asterisk-g#)", {})
vim.api.nvim_set_keymap("n","z*", "<Plug>(asterisk-z*)", {})
vim.api.nvim_set_keymap("n","gz*", "<Plug>(asterisk-gz*)", {})
vim.api.nvim_set_keymap("n","z#", "<Plug>(asterisk-z#)", {})
vim.api.nvim_set_keymap("n","gz#", "<Plug>(asterisk-gz#)", {})
vim.api.nvim_set_keymap("v", "*", "<Plug>(asterisk-*)", {})
vim.api.nvim_set_keymap("v", "#", "<Plug>(asterisk-#)", {})
vim.api.nvim_set_keymap("v","g*", "<Plug>(asterisk-g*)", {})
vim.api.nvim_set_keymap("v","g#", "<Plug>(asterisk-g#)", {})
vim.api.nvim_set_keymap("v","z*", "<Plug>(asterisk-z*)", {})
vim.api.nvim_set_keymap("v","gz*", "<Plug>(asterisk-gz*)", {})
vim.api.nvim_set_keymap("v","z#", "<Plug>(asterisk-z#)", {})
vim.api.nvim_set_keymap("v","gz#", "<Plug>(asterisk-gz#)", {})
vim.g["asterisk#keeppos"] = true
